FROM golang:1.13.6 AS builder

ENV APP_HOME /go/src/github.com/marceloagmelo/go-rabbitmq-send

ADD . $APP_HOME

WORKDIR $APP_HOME

 RUN go get ./... && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o go-rabbitmq-send && \
    rm -Rf /tmp/* && rm -Rf /var/tmp/*

###
# IMAGEM FINAL
###
FROM scratch
#FROM alpine:3.6
#RUN apk add --no-cache ca-certificates

ENV APP_BUILDER /go/src/github.com/marceloagmelo/go-rabbitmq-send/
ENV APP_HOME /opt/app

WORKDIR $APP_HOME

COPY --from=builder $APP_BUILDER/go-rabbitmq-send $APP_HOME/go-rabbitmq-send
COPY views $APP_HOME/views
COPY static $APP_HOME/static

#######################################################################
##### We have to expose image metada as label and ENV
#######################################################################
LABEL br.com.santander.imageowner="Corporate Techonology" \
      br.com.santander.description="RabbitMQ envio de mensagens runtime for node microservices" \
      br.com.santander.components="Golang Server"

ENV br.com.santander.imageowner="Corporate Techonology"
ENV br.com.santander.description="RabbitMQ envio de mensagens runtime for node microservices"
ENV br.com.santander.components="Golang Server"

ENV PATH $APP_HOME:$PATH

EXPOSE 8080

CMD [ "go-rabbitmq-send" ]
#ENTRYPOINT [ "$APP_HOME/go-rabbitmq-send" ]