export MYSQL_HOSTNAME="mysqldb"
export MYSQL_USER="user"
export MYSQL_PASSWORD="user123"
export MYSQL_ROOT_PASSWORD="admin123"
export MYSQL_DATABASE="mysqldbsample"
export MYSQL_PORT=3306

export RABBITMQ_DEFAULT_USER="user"
export RABBITMQ_DEFAULT_PASS="user123"
export RABBITMQ_ERLANG_COOKIE="12345"
export RABBITMQ_DEFAULT_VHOST="/"

export RABBITMQ_HOSTNAME="rabbitmq"
export RABBITMQ_USER="user"
export RABBITMQ_PASS="user123"
export RABBITMQ_PORT=5672
export RABBITMQ_VHOST="/"